### ISSUE TITLE
Campaign | Teams: home screen

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene-app#179]
As an app user the teams home screen gives me an overview of the main teams functionality appropriate to my role (#725). 

Some general points:
- Users can be in only one team at any time
- 10 users maximum per team

Acceptance criteria:
There are several distinct sections. 
- [ ] team profile section (if part of a team) #733 
- [ ] assigned elements section (if the team has been assigned routes or action areas) #736 
- [ ] member statistic area #196
- [ ] create new team link (only for Lokalkoordinator role) #297
- [ ] leave current team #300

The screenshot should be thought without the red elements of course:
<img width="444" height="642" alt="Image" src="https://github.com/user-attachments/assets/a0b2d770-b093-416a-8083-1b67cd013c53" />

Prototype (outdated): https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2757-16515&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

API endpoint references: 
https://github.com/verdigado/gruene-api/issues/88
https://github.com/verdigado/gruene-api/issues/89
https://github.com/verdigado/gruene-api/issues/90
https://github.com/verdigado/gruene-api/issues/91
https://github.com/verdigado/gruene-api/issues/249
https://github.com/verdigado/gruene-api/issues/252

Pollion reference: https://github.com/pollion/sunflower-app/issues/82

**Comment by judithwerner** [comment]
Welche Infos über das Teammitglied können potentiell eingeblendet werden?
Name, aber auch Kontaktdaten? 
Ein Bild, das nicht über die Sherpa aber das App-Profil eingepflegt werden kann?
@svenseeberg @ktmecking

**Comment by ktmecking** [comment]
> Welche Infos über das Teammitglied können potentiell eingeblendet werden? Name, aber auch Kontaktdaten? Ein Bild, das nicht über die Sherpa aber das App-Profil eingepflegt werden kann? @svenseeberg @ktmecking

Deine Vorschläge erscheinen mir grundsätzlich plausibel. Vielleicht können wir uns das mal gemeinsam ansehen.

**Comment by svenseeberg** [comment]
Der Plan ist, dass man über einen anderen Kanal den Einladungslink verschicken muss. D.h. man kennt die Personen, die man einlädt auch. Dementsprechend reicht eigentlich der Name.

**Comment by nscharioth** [comment]
Pollion reference: https://github.com/pollion/sunflower-app/issues/82

**Comment by nscharioth** [comment]
UX questions @leagerndt @JuliaFreitagBGSt:
- review maximum number of team members (5, 10, more?)?
- where is the team delete function to be found?

**Comment by nscharioth** [comment]
These are good questions.

A person can only ever be part of one team.

As such, I would say:
If a person is already a team member somewhere, he/she should not be shown as a potential team member yet before he/she accepts the invitation, which will lead to a team switch.

In consequence, persons who are not yet team members should also not be shown.

In both cases, however, the team invitation needs to be counted so that the max 10 is not over invited.

Can the invitation be accepted on the teams screen: We don't have a description for this process so I would say for 2025.12.0 this does not make sense. It is a good idea for a future feature though.

**Comment by Stift** [comment]
Might be true, but a notification is sth a user can discard and not actively act on that in that moment. The question is, where do I see me open invitations? I suggest we put above the team profile 'Mein Team' (see screen shot above) for each invitation a small invitation window with some team description and two actions (ACCEPT + DECLINE). You might also think it in this way, what do we see on the screen when I have not accepted the invitation yet?

**Comment by nscharioth** [comment]
I opened a new issue #785 for this topic. I suggest we move the discussion over there. @Stift 

@ungemeinfein we need UX input for such an overview of open invitations.
