### ISSUE TITLE
Campaign: Statistics Part II (for teams)

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene-app#196]
**Users can see campaign statistics for their team and globally to motivate themselves and compare their progress with others.**

If they are part of a team, users see an additional entry in their regular statistics
component: “my team”. This refers to their current team. If a user is not part of a team, the respective option is hidden.

Acceptance criteria:
- [ ] Number of doors recorded by my team 
- [ ] Number of poster recorded by my team 
- [ ] Number of flyers recorded by my team 

Pollion reference: https://github.com/pollion/sunflower-app/issues/161

API reference: https://github.com/verdigado/gruene-api/issues/252

**Comment by nscharioth** [comment]
Pollion reference: https://github.com/pollion/sunflower-app/issues/161

**Comment by nscharioth** [comment]
UX questions @leagerndt @JuliaFreitagBGSt 
- Why are posters, flyers and doors not treated the same?
- please also align with #178
