### ISSUE TITLE
Campaign: Area for Guests / Non-Members

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene-app#219]
**Nachdem ein Nicht-Parteimitglied über einen Einladungscode Zutritt zur App erhalten hat, kann es einen großen Teil der Wahlkampffunktionen nutzen.**
Siehe hierzu auch: "Einstellungen: Nicht-Mitglied einladen" #224 

Acceptance criteria:
- [ ] Die App funktioniert in diesem Fall nur auf der Hauptseite "Wahlkampf", sowie der Einstellungs-Seite.
- [ ] Alle anderen Hauptseiten, sowie die Wahlkampf-Unterseite "Team" führen zu einer Seite, die darüber aufklärt, dass die Funktionen nur Parteimitgliedern zur Verfügung stehen. #291 
- [ ] Hier wird auch ein Buttonfür den Beitritt zur Partei (externer Link zum Beitritt) eingeblendet. #292 
- [ ] Unter "Statistiken" werden entsprechend keine Statistiken von Teams oder Gliederungen angezeigt. #196
- [ ] Im Bereich "Einstellungen" fehlt die Seite "Nicht-Mitglied einladen". #224

![grafik](https://github.com/user-attachments/assets/f3b9e4c5-2fc1-46f9-b67d-56900e1cafa7)

![grafik](https://github.com/user-attachments/assets/2d2940b4-6e70-4030-88d0-78b83c98e85e)

Prototype: https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=3112-15003&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

Pollion reference: https://github.com/pollion/sunflower-app/issues/117

**Comment by nscharioth** [comment]
Pollion reference: https://github.com/pollion/sunflower-app/issues/117
