### ISSUE TITLE
Campaign | Teams: Create new team

### ISSUE THREAD

**Issue by nscharioth** [verdigado/gruene-app#297]
As an app user I want to be able to create a new team, if I have the role "Lokalkoordinator".

Acceptance criteria:
- [x] From the teams homescreen #179 the user can follow a link to create a new team. This opens up a popup.

1st popup screen:
- [x] The user needs to enter a team name 
- [x] The user needs to enter a team description #726
- [x] The user needs to decide on whether to join the new team #730
- [x] "Weiter" leads to the next screen in the teams creation process
- [x] Pressing on "X" stops the process without saving.

2nd popup screen:
- [x] The user needs to assign a party division #727

3rd popup screen:
- [x] The user needs to assign a team lead #301 

4th popup screen:
- [x] Inviting users opens up the teams search function in the next screen. #305 
- [x] A team member can be invited from the teams search function. #754 

----

Team name  
- Every team has a name  
- Name is created on team creation  
- Name is limited in characters min/max 
- Name can be edited (by team leads only) 
- Team names are validated for duplicates  

<img width="582" height="604" alt="Image" src="https://github.com/user-attachments/assets/21e0a721-8688-480c-ad34-17dfdc4436ac" />
<img width="596" height="400" alt="Image" src="https://github.com/user-attachments/assets/26767eb3-f355-42a3-a227-207af60a6bda" />
<img width="645" height="425" alt="Image" src="https://github.com/user-attachments/assets/dfb8cb5d-ed92-42e1-a398-b62822353bd0" />
<img width="601" height="426" alt="Image" src="https://github.com/user-attachments/assets/75b30fc3-6414-4458-bf73-e15221558ac6" />

Prototype (outdated): https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=3251-20871&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

API endpoint reference: https://github.com/verdigado/gruene-api/issues/88

API endpoint references: 
https://github.com/verdigado/gruene-api/issues/88
https://github.com/verdigado/gruene-api/issues/249

Pollion reference: 
https://github.com/pollion/sunflower-app/issues/86

**Comment by nscharioth** [comment]
A suggestion for simplification of the UX journey:
When a team is created only the team name has to be entered. Then the user is brought back to the teams homescreen. Team members can then be added in a follow-up step. So the 3rd and 4th screens would be cut from the initial team setup process here.
Ok? @leagerndt @JuliaFreitagBGSt

**Comment by nscharioth** [comment]
In my mind the description is still optional, so I would read it as "The user should enter a team description".
