### ISSUE TITLE
Campaign | Teams: Make team lead

### ISSUE THREAD

**Issue by nscharioth** [verdigado/gruene-app#301]
As a team lead I want to be able to assign other team members the role of team lead.

Assigning a team lead 

- Every team has at least 1 team lead  
- By default, the creator is the first team lead 
Additional team leads can be assigned at any time: 
- By inviting them 
- By promoting an existing team member 
Team leads can be downgraded to regular team members:
- By another team lead 
- By an admin 

Team lead role 
 - Each team has a minimum of 1 team lead 
- By default, the creator of the team becomes the teamlead 
- If they wish, creators can opt out of joining the team (and becoming the team lead) themselves, see “creating without joining” 
- Team leads can assign additional team leads (members of the team) 
- If last team lead leaves the team, a new teamlead needs to be assigned first  
Team lead has additional permissions:
- Invite members 
- Remove members  
- Edit team name  
- Edit team description  
- Archive team 

Acceptance criteria:
- [ ] popup to assign a new team lead
- [ ] In the edit team popup #299 it is possible to make another team member, who has accepted their invitation, a team lead. 

- [ ] Multiple people can be team leads.
- [ ] If this is done, the new team leader should be visible as such in the teams overview by a specific icon.

<img width="693" height="424" alt="Image" src="https://github.com/user-attachments/assets/96bbe893-ca98-4d7d-a51a-ee2e17b94e4e" />

Prototype (outdated): https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2743-11128&t=b8swD5IOAFfZ0OSo-1

API endpoint reference: https://github.com/verdigado/gruene-api/issues/89

Pollion reference: https://github.com/pollion/sunflower-app/issues/95

**Comment by nscharioth** [comment]
A definition of the team lead icon needs to be provided. @leagerndt
